name: actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-lint-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACTION_TOKEN }}
        
    - name: Update toolchain
      run: |
        rustup update
        rustup component add clippy
    
    - name: Install graphviz-dev
      run: sudo apt-get install -y graphviz-dev
      
    - name: Build
      run: |
        cd dot-viewer
        cargo build --verbose
        
    - name: Lint
      run: |
        cd dot-viewer
        cargo fmt -- --check
        cargo clippy -- -D warnings
      
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACTION_TOKEN }}
    
    - name: Install graphviz
      run: brew install graphviz
      
    - name: Build
      run: cargo build --verbose
